version: 2.1

jobs:
  

  build for many_linux:
    parameters:
      python_version:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/dipy
    environment:
     -img: quay.io/pypa/manylinux2014_aarch64
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - checkout
      - run:
          name: ️️🏗️ Wheel making
          command: |
             docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              quay.io/pypa/manylinux2014_aarch64 \
              bash -exc '/opt/python/<< parameters.python_version >>/bin/python -m venv .env && \
              source .env/bin/activate && \
              export PATH=$PATH:"/opt/python/<< parameters.python_version >>/bin" && \
              export INSTALL_TYPE=wheel && \
              export DEPENDS=cython numpy matplotlib h5py nibabel cvxpy tqdm && \
              export VENV_ARGS=--python=python && \
              export EXTRA_DEPENDS=scipy && \
              yum groupinstall "Development Tools" -y && \
              yum install man-pages -y && \
              ./tools/ci/install_dependencies.sh && \
              ./tools/ci/install.sh && \
              ./tools/ci/run_tests.sh && \
              deactivate'
                    

      
  
  

workflows:
  version: 2
  python3.7:
    jobs:
      
      - build for many_linux:
           matrix:
            parameters:
              python_version:
                - "cp37-cp37m"
                - "cp36-cp36m"
                - "cp38-cp38"
                - "cp39-cp39"
