name: PRE_WHEELS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PRE:
    uses: ./.github/workflows/test_template.yml
    with:
      runs-on: '["ubuntu-latest", ]'
      use-pre: true
      extra-depends: scikit_learn scipy statsmodels pandas tables
      
  wheeell:
     uses: ./.github/workflows/test_template.yml
     with:
       runs-on: '["ubuntu-latest", ]'
       arch: '["x86_64", "aarch64"]'
       python-version: '["3.9", "3.8", "3.7", "3.6"]'
       install-type: '["wheel", ]'
       depends : cython numpy matplotlib h5py nibabel cvxpy tqdm
       extra-depends: scipy
